spring.application.name=Library tool
spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

spring.jackson.serialization.indent-output=true
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null

logging.level.root=INFO
logging.level.com.lav.libtool=INFO
logging.level.org.springframework.web=WARN